# ./docker-compose.yml

version: '3.1'

services:
  db:
    image: andreechka/mysql57_my:v7_base_inside
#    image: andreechka/mysql8_my
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: my_db
#      MYSQL_USER: man_local
#      MYSQL_PASSWORD: 123qwe
#    command: --lower_case_table_names=2
#    volumes:
#      - ./mysql:/var/lib/mysql

    env_file:
      - env.list

    ports:
      - "3306:3306"


  web:
    build: ./php

        # etot obraz budet obshchat'sya s mysql
    links:
      - db

    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
#      - ./php/:/usr/local/etc/php
    ports:
      - "8100:80"
    stdin_open: true
    tty: true